email: "rishabnandibusiness@gmail.com"
full_name: "Rishab Nandi"
name: "Rishab"
background: |
  Rishab is the CEO and lead developer of Plmbr, a service booking marketplace and agentIC SaaS platform. 
  Plmbr specializes in:
  - Service booking automation through AI agents
  - Innovative "booking packets" concept for streamlined service bookings
  - Market research agents
  - Contract generation agents
  
  As both CEO and technical lead, Rishab has personally developed all of Plmbr's agent systems and oversees the company's technical and business strategy.

schedule_preferences: |
  - By default, schedule meetings for 30 minutes
  - Prioritize investor and partnership meetings
  - Early morning meetings preferred for investor calls
  - Keep afternoons for development and team sync-ups

background_preferences: |
  - Always mention Plmbr's unique approach to service bookings
  - Highlight the booking packets innovation when relevant
  - Emphasize our multi-agent ecosystem for different services
  - Reference our success in automating service bookings

response_preferences: |
  - Always respond to investor emails promptly and comprehensively
  - Be professional but show technical depth when discussing our agent systems
  - Highlight both business and technical achievements
  - When discussing technical aspects, demonstrate deep understanding of our agent architecture

timezone: "PST"

rewrite_preferences: |
  Rishab's email style guidelines:
  - Match the tone of the sender while maintaining CEO authority
  - Be professional but show technical expertise when relevant
  - Be concise but include key technical or business metrics when appropriate
  - With investors, always include progress updates and growth metrics
  - When discussing technical aspects, demonstrate deep knowledge of our agent systems
  - For partnership inquiries, emphasize our booking packets innovation
  - Always maintain a founder's perspective while being approachable

triage_no: |
  - Automated service notifications
  - Generic cold outreach
  - Spam emails
  - Automated calendar invitations not related to investors or partnerships

triage_notify: |
  - Investment-related documents
  - Partnership agreements
  - Technical architecture discussions
  - Team escalations
  - Legal documents
  - Important metrics reports
  - Strategic partnership opportunities

triage_email: |
  - All investor communications
  - Partnership inquiries
  - Technical collaboration requests
  - Team member questions
  - Customer success escalations
  - Strategic business opportunities
  - All emails about agent development or booking packets
  - Market research inquiries
  - Contract-related discussions

memory: true
